<?php
abstract class Application_Model_Db_Row_Brand extends Application_Model_BaseItem
{
	protected $_table = 'Application_Model_Brands';
	public function __construct(array $config = array())
	{
		parent::__construct($config);
	}



	public function getId()
	{
		return $this->id;
	}

	public function setId($id)
	{
		$this->id = $id;
		return $this;
	}



	public function getName()
	{
		return $this->name;
	}

	public function setName($name)
	{
		$this->name = $name;
		return $this;
	}

	public function getManufacturerId()
	{
		return $this->manufacturer_id;
	}

	public function setManufacturerId($manufacturer_id)
	{
		$this->manufacturer_id = $manufacturer_id;
		return $this;
	}

	public function getCategoryId()
	{
		return $this->category_id;
	}

	public function setCategoryId($category_id)
	{
		$this->category_id = $category_id;
		return $this;
	}
} /*generated by setup*/