<?php
class Application_Model_Db_Row_Product extends Zend_Db_Table_Row_Abstract{

	public function __construct(array $config = array())
	{
		parent::__construct($config);
	}



	public function getId()
	{
		return $this->id;
	}

	public function setId($id)
	{
		$this->id = $id;
		return $this;
	}

	public function getId()
	{
		return $this->id;
	}

	public function getName()
	{
		return $this->name;
	}

	public function setName($name)
	{
		$this->name = $name;
		return $this;
	}

	public function getDescription()
	{
		return $this->description;
	}

	public function setDescription($description)
	{
		$this->description = $description;
		return $this;
	}

	public function getColor()
	{
		return $this->color;
	}

	public function setColor($color)
	{
		$this->color = $color;
		return $this;
	}

	public function getSize()
	{
		return $this->size;
	}

	public function setSize($size)
	{
		$this->size = $size;
		return $this;
	}

	public function getPrice()
	{
		return $this->price;
	}

	public function setPrice($price)
	{
		$this->price = $price;
		return $this;
	}

	public function getBrandId()
	{
		return $this->brand_id;
	}

	public function setBrandId($brand_id)
	{
		$this->brand_id = $brand_id;
		return $this;
	}

	public function getRetailerId()
	{
		return $this->retailer_id;
	}

	public function setRetailerId($retailer_id)
	{
		$this->retailer_id = $retailer_id;
		return $this;
	}
} /*generated by setup*/