<?php
abstract class Application_Model_Db_Row_Product extends Application_Model_BaseItem
{
	protected $_table = 'Application_Model_Products';
	public function __construct(array $config = array())
	{
		parent::__construct($config);
	}



	public function getId()
	{
		return $this->id;
	}

	public function setId($id)
	{
		$this->id = $id;
		return $this;
	}



	public function getName()
	{
		return $this->name;
	}

	public function setName($name)
	{
		$this->name = $name;
		return $this;
	}

	public function getDescription()
	{
		return $this->description;
	}

	public function setDescription($description)
	{
		$this->description = $description;
		return $this;
	}

	public function getColor()
	{
		return $this->color;
	}

	public function setColor($color)
	{
		$this->color = $color;
		return $this;
	}

	public function getSize()
	{
		return $this->size;
	}

	public function setSize($size)
	{
		$this->size = $size;
		return $this;
	}

	public function getPrice()
	{
		return $this->price;
	}

	public function setPrice($price)
	{
		$this->price = $price;
		return $this;
	}

	public function getBrandId()
	{
		return $this->brand_id;
	}

	public function setBrandId($brand_id)
	{
		$this->brand_id = $brand_id;
		return $this;
	}

	public function getRetailerId()
	{
		return $this->retailer_id;
	}

	public function setRetailerId($retailer_id)
	{
		$this->retailer_id = $retailer_id;
		return $this;
	}

	public function getKeywords()
	{
		return $this->keywords;
	}

	public function setKeywords($keywords)
	{
		$this->keywords = $keywords;
		return $this;
	}

	public function getAdvertiserKeywords()
	{
		return $this->advertiser_keywords;
	}

	public function setAdvertiserKeywords($advertiser_keywords)
	{
		$this->advertiser_keywords = $advertiser_keywords;
		return $this;
	}

	public function getSku()
	{
		return $this->sku;
	}

	public function setSku($sku)
	{
		$this->sku = $sku;
		return $this;
	}

	public function getUpc()
	{
		return $this->upc;
	}

	public function setUpc($upc)
	{
		$this->upc = $upc;
		return $this;
	}

	public function getCurrency()
	{
		return $this->currency;
	}

	public function setCurrency($currency)
	{
		$this->currency = $currency;
		return $this;
	}

	public function getSaleprice()
	{
		return $this->saleprice;
	}

	public function setSaleprice($saleprice)
	{
		$this->saleprice = $saleprice;
		return $this;
	}

	public function getBuyUrl()
	{
		return $this->buy_url;
	}

	public function setBuyUrl($buy_url)
	{
		$this->buy_url = $buy_url;
		return $this;
	}

	public function getImpressionUrl()
	{
		return $this->impression_url;
	}

	public function setImpressionUrl($impression_url)
	{
		$this->impression_url = $impression_url;
		return $this;
	}

	public function getImageUrl()
	{
		return $this->image_url;
	}

	public function setImageUrl($image_url)
	{
		$this->image_url = $image_url;
		return $this;
	}

	public function getInStock()
	{
		return $this->in_stock;
	}

	public function setInStock($in_stock)
	{
		$this->in_stock = $in_stock;
		return $this;
	}

	public function getBrandName()
	{
		return $this->brand_name;
	}

	public function setBrandName($brand_name)
	{
		$this->brand_name = $brand_name;
		return $this;
	}

	public function getSimilarity()
	{
		return $this->similarity;
	}

	public function setSimilarity($similarity)
	{
		$this->similarity = $similarity;
		return $this;
	}

	public function getVisible()
	{
		return $this->visible;
	}

	public function setVisible($visible)
	{
		$this->visible = $visible;
		return $this;
	}

	public function getUpdatedAt()
	{
		return $this->updated_at;
	}

	public function setUpdatedAt($updated_at)
	{
		$this->updated_at = $updated_at;
		return $this;
	}

	public function getInstock()
	{
		return $this->instock;
	}

	public function setInstock($instock)
	{
		$this->instock = $instock;
		return $this;
	}

	public function getShippingCost()
	{
		return $this->shipping_cost;
	}

	public function setShippingCost($shipping_cost)
	{
		$this->shipping_cost = $shipping_cost;
		return $this;
	}

	public function getOnline()
	{
		return $this->online;
	}

	public function setOnline($online)
	{
		$this->online = $online;
		return $this;
	}
} /*generated by setup*/