<?php
abstract class Application_Model_Db_Row_ProductXProduct extends Application_Model_BaseItem
{
	protected $_table = 'Application_Model_ProductXProducts';
	public function __construct(array $config = array())
	{
		parent::__construct($config);
	}



	public function getId()
	{
		return $this->id;
	}

	public function setId($id)
	{
		$this->id = $id;
		return $this;
	}



	public function getProductId()
	{
		return $this->product_id;
	}

	public function setProductId($product_id)
	{
		$this->product_id = $product_id;
		return $this;
	}

	public function getRelatedProductId()
	{
		return $this->related_product_id;
	}

	public function setRelatedProductId($related_product_id)
	{
		$this->related_product_id = $related_product_id;
		return $this;
	}
} /*generated by setup*/