<?php
abstract class Application_Model_Db_Row_ProductFeeds extends Zend_Db_Table_Row_Abstract{

	public function __construct(array $config = array())
	{
		parent::__construct($config);
	}



	public function getId()
	{
		return $this->id;
	}

	public function setId($id)
	{
		$this->id = $id;
		return $this;
	}



	public function getFilename()
	{
		return $this->filename;
	}

	public function setFilename($filename)
	{
		$this->filename = $filename;
		return $this;
	}

	public function getStatus()
	{
		return $this->status;
	}

	public function setStatus($status)
	{
		$this->status = $status;
		return $this;
	}

	public function getCreatedAt()
	{
		return $this->created_at;
	}

	public function setCreatedAt($created_at)
	{
		$this->created_at = $created_at;
		return $this;
	}

	public function getProcessedAt()
	{
		return $this->processed_at;
	}

	public function setProcessedAt($processed_at)
	{
		$this->processed_at = $processed_at;
		return $this;
	}

	public function getRecordsProcessed()
	{
		return $this->records_processed;
	}

	public function setRecordsProcessed($records_processed)
	{
		$this->records_processed = $records_processed;
		return $this;
	}
} /*generated by setup*/