<?php
class Application_Model_Db_Row_Reccomendation extends Zend_Db_Table_Row_Abstract{

	public function __construct(array $config = array())
	{
		parent::__construct($config);
	}



	public function getId()
	{
		return $this->id;
	}

	public function setId($id)
	{
		$this->id = $id;
		return $this;
	}

	public function getId()
	{
		return $this->id;
	}

	public function getProductId()
	{
		return $this->product_id;
	}

	public function setProductId($product_id)
	{
		$this->product_id = $product_id;
		return $this;
	}

	public function getContent()
	{
		return $this->content;
	}

	public function setContent($content)
	{
		$this->content = $content;
		return $this;
	}

	public function getTitle()
	{
		return $this->title;
	}

	public function setTitle($title)
	{
		$this->title = $title;
		return $this;
	}
} /*generated by setup*/