<?php
abstract class Application_Model_Db_Row_Reminder extends Application_Model_BaseItem
{
	protected $_table = 'Application_Model_Reminders';
	public function __construct(array $config = array())
	{
		parent::__construct($config);
	}



	public function getId()
	{
		return $this->id;
	}

	public function setId($id)
	{
		$this->id = $id;
		return $this;
	}



	public function getUserId()
	{
		return $this->user_id;
	}

	public function setUserId($user_id)
	{
		$this->user_id = $user_id;
		return $this;
	}

	public function getShoplistId()
	{
		return $this->shoplist_id;
	}

	public function setShoplistId($shoplist_id)
	{
		$this->shoplist_id = $shoplist_id;
		return $this;
	}

	public function getName()
	{
		return $this->name;
	}

	public function setName($name)
	{
		$this->name = $name;
		return $this;
	}

	public function getDescription()
	{
		return $this->description;
	}

	public function setDescription($description)
	{
		$this->description = $description;
		return $this;
	}

	public function getImageUrl()
	{
		return $this->image_url;
	}

	public function setImageUrl($image_url)
	{
		$this->image_url = $image_url;
		return $this;
	}

	public function getPrice()
	{
		return $this->price;
	}

	public function setPrice($price)
	{
		$this->price = $price;
		return $this;
	}

	public function getStoreName()
	{
		return $this->store_name;
	}

	public function setStoreName($store_name)
	{
		$this->store_name = $store_name;
		return $this;
	}

	public function getStoreLongitude()
	{
		return $this->store_longitude;
	}

	public function setStoreLongitude($store_longitude)
	{
		$this->store_longitude = $store_longitude;
		return $this;
	}

	public function getStoreLattitude()
	{
		return $this->store_lattitude;
	}

	public function setStoreLattitude($store_lattitude)
	{
		$this->store_lattitude = $store_lattitude;
		return $this;
	}
} /*generated by setup*/