<?php
abstract class Application_Model_Db_Row_Retailer extends Application_Model_BaseItem
{
	protected $_table = 'Application_Model_Retailers';
	public function __construct(array $config = array())
	{
		parent::__construct($config);
	}



	public function getId()
	{
		return $this->id;
	}

	public function setId($id)
	{
		$this->id = $id;
		return $this;
	}



	public function getName()
	{
		return $this->name;
	}

	public function setName($name)
	{
		$this->name = $name;
		return $this;
	}

	public function getUrl()
	{
		return $this->url;
	}

	public function setUrl($url)
	{
		$this->url = $url;
		return $this;
	}

	public function getLastUpdate()
	{
		return $this->last_update;
	}

	public function setLastUpdate($last_update)
	{
		$this->last_update = $last_update;
		return $this;
	}

	public function getCategoryId()
	{
		return $this->category_id;
	}

	public function setCategoryId($category_id)
	{
		$this->category_id = $category_id;
		return $this;
	}

	public function getState()
	{
		return $this->state;
	}

	public function setState($state)
	{
		$this->state = $state;
		return $this;
	}

	public function getProcessor()
	{
		return $this->processor;
	}

	public function setProcessor($processor)
	{
		$this->processor = $processor;
		return $this;
	}
} /*generated by setup*/