<?php
abstract class Application_Model_Db_Row_ShoppingListItem extends Application_Model_BaseItem
{
	protected $_table = 'Application_Model_ShoppingListItems';
	public function __construct(array $config = array())
	{
		parent::__construct($config);
	}



	public function getId()
	{
		return $this->id;
	}

	public function setId($id)
	{
		$this->id = $id;
		return $this;
	}



	public function getShoppingListId()
	{
		return $this->shopping_list_id;
	}

	public function setShoppingListId($shopping_list_id)
	{
		$this->shopping_list_id = $shopping_list_id;
		return $this;
	}

	public function getProductId()
	{
		return $this->product_id;
	}

	public function setProductId($product_id)
	{
		$this->product_id = $product_id;
		return $this;
	}

	public function getReminder()
	{
		return $this->reminder;
	}

	public function setReminder($reminder)
	{
		$this->reminder = $reminder;
		return $this;
	}

	public function getCreatedAt()
	{
		return $this->created_at;
	}

	public function setCreatedAt($created_at)
	{
		$this->created_at = $created_at;
		return $this;
	}
} /*generated by setup*/