<?php
abstract class Application_Model_Db_Row_ThemeXCategory extends Application_Model_BaseItem
{
	protected $_table = 'Application_Model_ThemeXCategories';
	public function __construct(array $config = array())
	{
		parent::__construct($config);
	}



	public function getId()
	{
		return $this->id;
	}

	public function setId($id)
	{
		$this->id = $id;
		return $this;
	}



	public function getThemeId()
	{
		return $this->theme_id;
	}

	public function setThemeId($theme_id)
	{
		$this->theme_id = $theme_id;
		return $this;
	}

	public function getCategoryId()
	{
		return $this->category_id;
	}

	public function setCategoryId($category_id)
	{
		$this->category_id = $category_id;
		return $this;
	}
} /*generated by setup*/