<?php
abstract class Application_Model_Db_Row_Translation extends Application_Model_BaseItem
{
	protected $_table = 'Application_Model_Translations';
	public function __construct(array $config = array())
	{
		parent::__construct($config);
	}



	public function getId()
	{
		return $this->id;
	}

	public function setId($id)
	{
		$this->id = $id;
		return $this;
	}



	public function getCombination()
	{
		return $this->combination;
	}

	public function setCombination($combination)
	{
		$this->combination = $combination;
		return $this;
	}

	public function getReplacement()
	{
		return $this->replacement;
	}

	public function setReplacement($replacement)
	{
		$this->replacement = $replacement;
		return $this;
	}
} /*generated by setup*/