<?php
abstract class Application_Model_Db_Row_UserInterest extends Zend_Db_Table_Row_Abstract{

	public function __construct(array $config = array())
	{
		parent::__construct($config);
	}



	public function getId()
	{
		return $this->id;
	}

	public function setId($id)
	{
		$this->id = $id;
		return $this;
	}



	public function getUserId()
	{
		return $this->user_id;
	}

	public function setUserId($user_id)
	{
		$this->user_id = $user_id;
		return $this;
	}

	public function getInterestId()
	{
		return $this->interest_id;
	}

	public function setInterestId($interest_id)
	{
		$this->interest_id = $interest_id;
		return $this;
	}
} /*generated by setup*/