<?php
abstract class Application_Model_Db_Row_UserFacebook extends Application_Model_BaseItem
{
	protected $_table = 'Application_Model_UserFacebooks';
	public function __construct(array $config = array())
	{
		parent::__construct($config);
	}



	public function getId()
	{
		return $this->id;
	}

	public function setId($id)
	{
		$this->id = $id;
		return $this;
	}



	public function getUserId()
	{
		return $this->user_id;
	}

	public function setUserId($user_id)
	{
		$this->user_id = $user_id;
		return $this;
	}

	public function getAccessToken()
	{
		return $this->access_token;
	}

	public function setAccessToken($access_token)
	{
		$this->access_token = $access_token;
		return $this;
	}

	public function getExpirationDate()
	{
		return $this->expiration_date;
	}

	public function setExpirationDate($expiration_date)
	{
		$this->expiration_date = $expiration_date;
		return $this;
	}
} /*generated by setup*/