<?php
class Application_Model_Db_Row_User extends Zend_Db_Table_Row_Abstract{

	public function __construct(array $config = array())
	{
		parent::__construct($config);
	}



	public function getId()
	{
		return $this->id;
	}

	public function setId($id)
	{
		$this->id = $id;
		return $this;
	}

	public function getId()
	{
		return $this->id;
	}

	public function getFirstName()
	{
		return $this->first_name;
	}

	public function setFirstName($first_name)
	{
		$this->first_name = $first_name;
		return $this;
	}

	public function getLastName()
	{
		return $this->last_name;
	}

	public function setLastName($last_name)
	{
		$this->last_name = $last_name;
		return $this;
	}

	public function getFollowers()
	{
		return $this->followers;
	}

	public function setFollowers($followers)
	{
		$this->followers = $followers;
		return $this;
	}

	public function getAge()
	{
		return $this->age;
	}

	public function setAge($age)
	{
		$this->age = $age;
		return $this;
	}

	public function getLocation()
	{
		return $this->location;
	}

	public function setLocation($location)
	{
		$this->location = $location;
		return $this;
	}

	public function getGender()
	{
		return $this->gender;
	}

	public function setGender($gender)
	{
		$this->gender = $gender;
		return $this;
	}

	public function getShoeSize()
	{
		return $this->shoe_size;
	}

	public function setShoeSize($shoe_size)
	{
		$this->shoe_size = $shoe_size;
		return $this;
	}

	public function getPantsSize()
	{
		return $this->pants_size;
	}

	public function setPantsSize($pants_size)
	{
		$this->pants_size = $pants_size;
		return $this;
	}

	public function getShirtSize()
	{
		return $this->shirt_size;
	}

	public function setShirtSize($shirt_size)
	{
		$this->shirt_size = $shirt_size;
		return $this;
	}
} /*generated by setup*/