<?php
abstract class Application_Model_Db_Table_Brands extends Zend_Db_Table_Abstract
{
	protected $_name = 'brand';
	protected $_rowClass = 'Application_Model_Brand';
//	protected $_primary = 'brand_id';
	protected $_primary = 'id';
/**
	 *
	 * @param integer $id
	 * @return Application_Model_Brand 
	 */
	public function fetch($id)
	{
		//return $this->fetchRow('brand_id=' . $id);
		return $this->fetchRow('id=' . $id);
	}
} /*generated by setup*/