<?php
class Application_Model_Db_Table_CategoryProducts extends Zend_Db_Table_Abstract
{
	protected $_name = 'category_product';
	protected $_rowClass = 'Application_Model_CategoryProduct';
	protected $_primary = 'category_product_id';
/**
	 *
	 * @param integer $id
	 * @return Application_Model_Thread 
	 */
	public function fetch($id)
	{
		return $this->fetchRow('category_product_id=' . $id);
	}
} /*generated by setup*/