<?php
abstract class Application_Model_Db_Table_Images extends Zend_Db_Table_Abstract
{
	protected $_name = 'image';
	protected $_rowClass = 'Application_Model_Image';
//	protected $_primary = 'image_id';
	protected $_primary = 'id';
/**
	 *
	 * @param integer $id
	 * @return Application_Model_Image 
	 */
	public function fetch($id)
	{
		//return $this->fetchRow('image_id=' . $id);
		return $this->fetchRow('id=' . $id);
	}
} /*generated by setup*/