<?php
abstract class Application_Model_Db_Table_Locations extends Zend_Db_Table_Abstract
{
	protected $_name = 'location';
	protected $_rowClass = 'Application_Model_Location';
//	protected $_primary = 'location_id';
	protected $_primary = 'id';
/**
	 *
	 * @param integer $id
	 * @return Application_Model_Location 
	 */
	public function fetch($id)
	{
		//return $this->fetchRow('location_id=' . $id);
		return $this->fetchRow('id=' . $id);
	}
} /*generated by setup*/