<?php
abstract class Application_Model_Db_Table_ProductFeeds extends Zend_Db_Table_Abstract
{
	protected $_name = 'product_feed';
	protected $_rowClass = 'Application_Model_ProductFeed';
//	protected $_primary = 'product_feed_id';
	protected $_primary = 'id';
/**
	 *
	 * @param integer $id
	 * @return Application_Model_ProductFeed 
	 */
	public function fetch($id)
	{
		//return $this->fetchRow('product_feed_id=' . $id);
		return $this->fetchRow('id=' . $id);
	}
} /*generated by setup*/