<?php
abstract class Application_Model_Db_Table_ProductFeedss extends Zend_Db_Table_Abstract
{
	protected $_name = 'product_feeds';
	protected $_rowClass = 'Application_Model_ProductFeeds';
//	protected $_primary = 'product_feeds_id';
	protected $_primary = 'id';
/**
	 *
	 * @param integer $id
	 * @return Application_Model_ProductFeeds 
	 */
	public function fetch($id)
	{
		//return $this->fetchRow('product_feeds_id=' . $id);
		return $this->fetchRow('id=' . $id);
	}
} /*generated by setup*/