<?php
abstract class Application_Model_Db_Table_ProductLocations extends Zend_Db_Table_Abstract
{
	protected $_name = 'product_location';
	protected $_rowClass = 'Application_Model_ProductLocation';
//	protected $_primary = 'product_location_id';
	protected $_primary = 'id';
/**
	 *
	 * @param integer $id
	 * @return Application_Model_Thread 
	 */
	public function fetch($id)
	{
		//return $this->fetchRow('product_location_id=' . $id);
		return $this->fetchRow('id=' . $id);
	}
} /*generated by setup*/