<?php
class Application_Model_Db_Table_ProductRelations extends Zend_Db_Table_Abstract
{
	protected $_name = 'product_relation';
	protected $_rowClass = 'Application_Model_ProductRelation';
	protected $_primary = 'product_relation_id';
/**
	 *
	 * @param integer $id
	 * @return Application_Model_Thread 
	 */
	public function fetch($id)
	{
		return $this->fetchRow('product_relation_id=' . $id);
	}
} /*generated by setup*/