<?php
abstract class Application_Model_Db_Table_Reccomendations extends Application_Model_BaseCollection
{
	protected $_name = 'reccomendation';
	protected $_rowClass = 'Application_Model_Reccomendation';
//	protected $_primary = 'reccomendation_id';
	protected $_primary = 'id';
/**
	 *
	 * @param integer $id
	 * @return Application_Model_Reccomendation 
	 */
	public function fetch($id)
	{
		//return $this->fetchRow('reccomendation_id=' . $id);
		return $this->fetchRow('id=' . $id);
	}
} /*generated by setup*/