<?php
class Application_Model_Db_Table_Reccomendations extends Zend_Db_Table_Abstract
{
	protected $_name = 'reccomendation';
	protected $_rowClass = 'Application_Model_Reccomendation';
	protected $_primary = 'reccomendation_id';
/**
	 *
	 * @param integer $id
	 * @return Application_Model_Thread 
	 */
	public function fetch($id)
	{
		return $this->fetchRow('reccomendation_id=' . $id);
	}
} /*generated by setup*/