<?php
abstract class Application_Model_Db_Table_Reminders extends Application_Model_BaseCollection
{
	protected $_name = 'reminder';
	protected $_rowClass = 'Application_Model_Reminder';
//	protected $_primary = 'reminder_id';
	protected $_primary = 'id';
/**
	 *
	 * @param integer $id
	 * @return Application_Model_Reminder 
	 */
	public function fetch($id)
	{
		//return $this->fetchRow('reminder_id=' . $id);
		return $this->fetchRow('id=' . $id);
	}
} /*generated by setup*/