<?php
class Application_Model_Db_Table_Retailers extends Zend_Db_Table_Abstract
{
	protected $_name = 'retailer';
	protected $_rowClass = 'Application_Model_Retailer';
	protected $_primary = 'retailer_id';
/**
	 *
	 * @param integer $id
	 * @return Application_Model_Thread 
	 */
	public function fetch($id)
	{
		return $this->fetchRow('retailer_id=' . $id);
	}
} /*generated by setup*/