<?php
abstract class Application_Model_Db_Table_ShoppingLists extends Zend_Db_Table_Abstract
{
	protected $_name = 'shopping_list';
	protected $_rowClass = 'Application_Model_ShoppingList';
//	protected $_primary = 'shopping_list_id';
	protected $_primary = 'id';
/**
	 *
	 * @param integer $id
	 * @return Application_Model_Thread 
	 */
	public function fetch($id)
	{
		//return $this->fetchRow('shopping_list_id=' . $id);
		return $this->fetchRow('id=' . $id);
	}
} /*generated by setup*/