<?php
abstract class Application_Model_Db_Table_ThemeCategorys extends Zend_Db_Table_Abstract
{
	protected $_name = 'theme_category';
	protected $_rowClass = 'Application_Model_ThemeCategory';
//	protected $_primary = 'theme_category_id';
	protected $_primary = 'id';
/**
	 *
	 * @param integer $id
	 * @return Application_Model_Thread 
	 */
	public function fetch($id)
	{
		//return $this->fetchRow('theme_category_id=' . $id);
		return $this->fetchRow('id=' . $id);
	}
} /*generated by setup*/