<?php
abstract class Application_Model_Db_Table_ThemeXCategories extends Zend_Db_Table_Abstract
{
	protected $_name = 'theme_x_category';
	protected $_rowClass = 'Application_Model_ThemeXCategory';
//	protected $_primary = 'theme_x_category_id';
	protected $_primary = 'id';
/**
	 *
	 * @param integer $id
	 * @return Application_Model_ThemeXCategory 
	 */
	public function fetch($id)
	{
		//return $this->fetchRow('theme_x_category_id=' . $id);
		return $this->fetchRow('id=' . $id);
	}
} /*generated by setup*/