<?php
abstract class Application_Model_Db_Table_Themes extends Zend_Db_Table_Abstract
{
	protected $_name = 'theme';
	protected $_rowClass = 'Application_Model_Theme';
//	protected $_primary = 'theme_id';
	protected $_primary = 'id';
/**
	 *
	 * @param integer $id
	 * @return Application_Model_Thread 
	 */
	public function fetch($id)
	{
		//return $this->fetchRow('theme_id=' . $id);
		return $this->fetchRow('id=' . $id);
	}
} /*generated by setup*/