<?php
abstract class Application_Model_Db_Table_Translations extends Application_Model_BaseCollection
{
	protected $_name = 'translation';
	protected $_rowClass = 'Application_Model_Translation';
//	protected $_primary = 'translation_id';
	protected $_primary = 'id';
/**
	 *
	 * @param integer $id
	 * @return Application_Model_Translation 
	 */
	public function fetch($id)
	{
		//return $this->fetchRow('translation_id=' . $id);
		return $this->fetchRow('id=' . $id);
	}
} /*generated by setup*/