<?php
class Application_Model_Db_Table_Users extends Zend_Db_Table_Abstract
{
	protected $_name = 'user';
	protected $_rowClass = 'Application_Model_User';
	protected $_primary = 'user_id';
/**
	 *
	 * @param integer $id
	 * @return Application_Model_Thread 
	 */
	public function fetch($id)
	{
		return $this->fetchRow('user_id=' . $id);
	}
} /*generated by setup*/