<?php
abstract class Application_Model_Db_Table_UserFacebooks extends Zend_Db_Table_Abstract
{
	protected $_name = 'user_facebook';
	protected $_rowClass = 'Application_Model_UserFacebook';
//	protected $_primary = 'user_facebook_id';
	protected $_primary = 'id';
/**
	 *
	 * @param integer $id
	 * @return Application_Model_Thread 
	 */
	public function fetch($id)
	{
		//return $this->fetchRow('user_facebook_id=' . $id);
		return $this->fetchRow('id=' . $id);
	}
} /*generated by setup*/