<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Irequest management</title>
<?php $this->headLink()->appendStylesheet('/media/css/global.css') ?>
<?php $this->headLink()->appendStylesheet('/media/css/jquery.mobile-1.0.1.css') ?>
<?php //$this->headLink()->appendStylesheet('/media/css/iefix.css', 'screen', 'lt IE 7') ?>   
<?php echo $this->cssHelper() ?>  
<?php $this->headScript()->appendFile('/media/js/jquery.min.js') ?>
<?php $this->headScript()->appendFile('/media/js/jquery.mobile-1.0.1.js') ?>
<?php //$this->headScript()->appendFile('/media/js/global.js') ?>

<?php $this->javascriptHelper() ?>
<?php echo $this->headScript() ?>
