<html>
    <head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="viewport" content="width=320, initial-scale=1"> 
	<title>testo</title>
	<?php //$this->headLink()->appendStylesheet('/media/css/global.css') ?>
	<?php //$this->headLink()->appendStylesheet('/media/css/iefix.css', 'screen', 'lt IE 7') ?>   
	<?php //echo $this->cssHelper() ?>  
	<?php //$this->headScript()->appendFile('/media/js/jquery.min.js') ?>
	<?php //$this->headScript()->appendFile('/media/js/global.js') ?>

	<?php //$this->javascriptHelper() ?>
	<?php //echo $this->headScript() ?>
	
    </head>
    <body>
	<?php echo $this->layout()->content ?>
    </body>
</html>